// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ロシア語単語データ  /  Данные русских слов
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// アクセント記号の入力方法：
//   母音の直後に U+0301（結合アクセント）を付けます。
//   例: е́ (е + ́)、а́ (а + ́)、и́ (и + ́)
//   ё は常に強勢なのでそのまま使えます。
//
// 管理ページ (admin.html) からも追加・編集・エクスポートができます。
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

const WORD_DATA = {
  version: 1,
  lessons: [
    {
      id: 1,
      title: "挨拶・基本表現",
      words: [
        { japanese: "こんにちは（くだけた言い方）", russian: "приве\u0301т" },
        { japanese: "こんにちは（丁寧な言い方）", russian: "здра\u0301вствуйте" },
        { japanese: "ありがとう", russian: "спаси\u0301бо" },
        { japanese: "どういたしまして／どうぞ", russian: "пожа\u0301луйста" },
        { japanese: "はい", russian: "да" },
        { japanese: "いいえ", russian: "нет" },
        { japanese: "さようなら（くだけた言い方）", russian: "пока\u0301" },
        { japanese: "さようなら（丁寧な言い方）", russian: "до свида\u0301ния" },
        { japanese: "おはようございます", russian: "до\u0301брое у\u0301тро" },
        { japanese: "こんにちは（昼の挨拶）", russian: "до\u0301брый день" },
        { japanese: "こんばんは", russian: "до\u0301брый ве\u0301чер" },
        { japanese: "おやすみなさい", russian: "споко\u0301йной но\u0301чи" },
        { japanese: "すみません（呼びかけ）", russian: "извини\u0301те" },
        { japanese: "ごめんなさい", russian: "прости\u0301те" },
        { japanese: "元気ですか？", russian: "как дела\u0301?" },
        { japanese: "元気です", russian: "хорошо\u0301" },
        { japanese: "よくないです", russian: "пло\u0301хо" },
        { japanese: "わかりません", russian: "не понима\u0301ю" },
        { japanese: "もう一度言ってください", russian: "повтори\u0301те, пожа\u0301луйста" },
        { japanese: "お名前は？", russian: "как вас зову\u0301т?" },
        { japanese: "私の名前は〜です", russian: "меня\u0301 зову\u0301т..." },
        { japanese: "はじめまして", russian: "о\u0301чень прия\u0301тно" },
        { japanese: "ようこそ", russian: "добро\u0301 пожа\u0301ловать" }
      ]
    },
    {
      id: 2,
      title: "数字",
      words: [
        { japanese: "0", russian: "ноль" },
        { japanese: "1", russian: "оди\u0301н" },
        { japanese: "2", russian: "два" },
        { japanese: "3", russian: "три" },
        { japanese: "4", russian: "четы\u0301ре" },
        { japanese: "5", russian: "пять" },
        { japanese: "6", russian: "шесть" },
        { japanese: "7", russian: "семь" },
        { japanese: "8", russian: "во\u0301семь" },
        { japanese: "9", russian: "де\u0301вять" },
        { japanese: "10", russian: "де\u0301сять" },
        { japanese: "11", russian: "оди\u0301ннадцать" },
        { japanese: "12", russian: "двена\u0301дцать" },
        { japanese: "13", russian: "трина\u0301дцать" },
        { japanese: "14", russian: "четы\u0301рнадцать" },
        { japanese: "15", russian: "пятна\u0301дцать" },
        { japanese: "16", russian: "шестна\u0301дцать" },
        { japanese: "17", russian: "семна\u0301дцать" },
        { japanese: "18", russian: "восемна\u0301дцать" },
        { japanese: "19", russian: "девятна\u0301дцать" },
        { japanese: "20", russian: "два\u0301дцать" },
        { japanese: "30", russian: "три\u0301дцать" },
        { japanese: "40", russian: "со\u0301рок" },
        { japanese: "50", russian: "пятьдеся\u0301т" },
        { japanese: "100", russian: "сто" },
        { japanese: "1,000（千）", russian: "ты\u0301сяча" },
        { japanese: "1,000,000（百万）", russian: "миллио\u0301н" }
      ]
    },
    {
      id: 3,
      title: "Урок 1",
      words: [
        { japanese: "これは", russian: "э\u0301то" },
        { japanese: "家屋", russian: "дом" },
        { japanese: "部屋", russian: "ко\u0301мната" },
        { japanese: "お母さん", russian: "ма\u0301ма" },
        { japanese: "窓", russian: "окно\u0301" },
        { japanese: "お父さん", russian: "па\u0301па" },
        { japanese: "机", russian: "стол" },
        { japanese: "椅子", russian: "стул" },
        { japanese: "在宅の", russian: "до\u0301ма" },
        { japanese: "あそこに", russian: "там" },
        { japanese: "ほら", russian: "вот" },
        { japanese: "と", russian: "и" }
      ]
    },
    {
      id: 4,
      title: "Урок 2",
      words: [
        { japanese: "私", russian: "я" },
        { japanese: "あなた,あなた方", russian: "вы" },
        { japanese: "水", russian: "во\u0301да" },
        { japanese: "新聞", russian: "газе\u0301та" },
        { japanese: "本", russian: "кни\u0301га" },
        { japanese: "海", russian: "мо\u0301ре" },
        { japanese: "湖", russian: "о\u0301зеро" },
        { japanese: "公園", russian: "парк" },
        { japanese: "教授", russian: "профе\u0301ссор" },
        { japanese: "川", russian: "река\u0301" },
        { japanese: "汁,ジュース", russian: "сок" },
        { japanese: "学生(男性)", russian: "студе\u0301нт" },
        { japanese: "学生(女性)", russian: "студе\u0301нтка" },
        { japanese: "ここに", russian: "здесь" },
        { japanese: "はい", russian: "да" },
        { japanese: "いいえ", russian: "нет" },
        { japanese: "〜ない", russian: "не" },
      ]
    },
    {
      id: 5,
      title: "Урок 3",
      words: [
        { japanese: "誰", russian: "кто" },
        { japanese: "何", russian: "что" },
        { japanese: "どこ", russian: "где" },
        { japanese: "彼", russian: "он" },
        { japanese: "彼女", russian: "она\u0301" },
        { japanese: "彼等", russian: "они\u0301" },
        { japanese: "兄弟", russian: "брат" },
        { japanese: "雑誌", russian: "журна\u0301л" },
        { japanese: "ジャーナリスト(男性)", russian: "журнали\u0301ст" },
        { japanese: "郵便局", russian: "по\u0301чта" },
        { japanese: "姉妹", russian: "сестра\u0301" },
        { japanese: "辞典", russian: "слова\u0301рь" },
        { japanese: "小中学校の教師(男性)", russian: "учи\u0301тель" },
        { japanese: "日本人(女性)", russian: "япо\u0301нка" },
        { japanese: "同様に", russian: "то\u0301же" },
      ]
    },
    {
      id: 6,
      title: "Урок 4",
      words: [
        { japanese: "私達", russian: "мы" },
        { japanese: "それ", russian: "оно\u0301" },
        { japanese: "君", russian: "ты" },
        { japanese: "あなたの,あなた方の", russian: "ваш" },
        { japanese: "彼の", russian: "его\u0301" },
        { japanese: "彼女の", russian: "её" },
        { japanese: "彼等の", russian: "их" },
        { japanese: "私の", russian: "мой" },
        { japanese: "私達の", russian: "наш" },
        { japanese: "君の", russian: "твой" },
        { japanese: "誰の", russian: "чей" },
        { japanese: "おじさん", russian: "дя\u0301дя" },
        { japanese: "名前", russian: "и\u0301мя" },
        { japanese: "美術館", russian: "музе\u0301й" },
        { japanese: "週", russian: "неде\u0301ля" },
        { japanese: "作家(男性)", russian: "писа\u0301тель" },
        { japanese: "手紙", russian: "письмо\u0301" },
        { japanese: "野原", russian: "по\u0301ле" },
        { japanese: "両親", russian: "роди\u0301тели" },
        { japanese: "子供", russian: "де\u0301ти" },
        { japanese: "眼鏡", russian: "очки\u0301" },
        { japanese: "時計", russian: "часы\u0301" },
        { japanese: "お金", russian: "де\u0301ньги" },
        { japanese: "ノート", russian: "тетра\u0301дь" },
        { japanese: "教科書", russian: "уче\u0301бник" },
        { japanese: "だが,その一方", russian: "а" },
        { japanese: "場所,席", russian: "ме\u0301сто" },
        { japanese: "面積,広場", russian: "пло\u0301щадь" },
        { japanese: "単語", russian: "сло\u0301во" },
        { japanese: "犬(女性)", russian: "соба\u0301ка" },
        { japanese: "犬(男性)", russian: "пёс" },
        { japanese: "おばさん", russian: "тётя" },
        { japanese: "初等中等教育学校", russian: "шко\u0301ла" },
        { japanese: "祖母", russian: "ба\u0301бушка" },
        { japanese: "医師", russian: "врач" },
        { japanese: "祖父", russian: "де\u0301душка" },
        { japanese: "母", russian: "мать" },
        { japanese: "父", russian: "оте\u0301ц" },
        { japanese: "家族", russian: "семья\u0301" },
        { japanese: "写真", russian: "фотогра\u0301фия" },
        { japanese: "そばに", russian: "ря\u0301дом" },
        { japanese: "右に", russian: "спра\u0301ва" }
      ]
    },
    {
      id: 7,
      title: "Урок 5",
      words: [
        { japanese: "この", russian: "э\u0301тот" },
        { japanese: "町", russian: "го\u0301род" },
        { japanese: "衣服", russian: "пла\u0301тье" },
        { japanese: "ラジオ", russian: "ра\u0301дио" },
        { japanese: "どんな", russian: "како\u0301й" },
        { japanese: "若い", russian: "молодо\u0301й" },
        { japanese: "新しい", russian: "но\u0301вый" },
        { japanese: "紺色の", russian: "си\u0301ний" },
        { japanese: "老いた", russian: "ста\u0301рый" },
        { japanese: "よく,よい", russian: "хорошо\u0301" },
        { japanese: "作る,する", russian: "де\u0301лать" },
        { japanese: "〜について知っている", russian: "знать" },
        { japanese: "聴講する", russian: "слу\u0301шать" },
        { japanese: "読む", russian: "чита\u0301ть" },
        { japanese: "或いは", russian: "и\u0301ли" },
        { japanese: "話", russian: "расска\u0301з" },
        { japanese: "面白い", russian: "интере\u0301сный" },
        { japanese: "美しい", russian: "краси\u0301вый" },
        { japanese: "夏", russian: "ле\u0301то" },
        { japanese: "働く", russian: "рабо\u0301тать" },
        { japanese: "今日", russian: "сего\u0301дня" },
        { japanese: "夕方", russian: "ве\u0301чер" },
        { japanese: "昼", russian: "де\u0301нь" },
        { japanese: "天気", russian: "пого\u0301да" },
        { japanese: "中等高等教育の教師(男性)", russian: "преподава\u0301тель" },
        { japanese: "本文", russian: "текст" },
        { japanese: "授業,課題", russian: "уро\u0301к" },
        { japanese: "朝", russian: "у\u0301тро" },
        { japanese: "善良な", russian: "до\u0301брый" },
        { japanese: "上等の", russian: "хоро\u0301ший" },
        { japanese: "大声で", russian: "гро\u0301мко" },
        { japanese: "緩慢に", russian: "ме\u0301дленно" },
        { japanese: "あとで", russian: "пото\u0301м" },
        { japanese: "今", russian: "сейча\u0301с" },
        { japanese: "〜の責任を持つ", russian: "отвеча\u0301ть" },
        { japanese: "言語を解する", russian: "понима\u0301ть" },
        { japanese: "〜を問う", russian: "спра\u0301шивать" },
        { japanese: "…も…も", russian: "и, и…" }
      ]
    },
    {
      id: 8,
      title: "Урок 6",
      words: [
        { japanese: "棚", russian: "по\u0301лка" },
        { japanese: "ロシアの,ロシア人の", russian: "ру\u0301сский" },
        { japanese: "ダイニングルーム,食堂", russian: "столо\u0301вая" },
        { japanese: "舌", russian: "язы\u0301к" },
        { japanese: "大きい", russian: "большо\u0301й" },
        { japanese: "悪い", russian: "плохо\u0301й" },
        { japanese: "話す", russian: "говори\u0301ть" },
        { japanese: "学ぶ,研究する", russian: "изуча\u0301ть" },
        { japanese: "横になっている", russian: "лежа\u0301ть" },
        { japanese: "顔を出している,向いている", russian: "смотре\u0301ть" },
        { japanese: "擁護する,主張する", russian: "стоя\u0301ть" },
        { japanese: "~の中へ,~を,~になる,~を通じ", russian: "в" },
        { japanese: "~へ,~に", russian: "на" },
        { japanese: "~に,~の側に", russian: "о" },
        { japanese: "テレビ", russian: "телеви\u0301зор" },
        { japanese: "映画", russian: "фильм" },
        { japanese: "夏に", russian: "ле\u0301том" },
        { japanese: "非常に", russian: "о\u0301чень" },
        { japanese: "悪く,悪い", russian: "пло\u0301хо" },
        { japanese: "休憩する", russian: "отдыха\u0301ть" },
        { japanese: "英語で,英国風に", russian: "по-англи\u0301йски" },
        { japanese: "ロシア語で,ロシア風に", russian: "по-ру\u0301сски" },
        { japanese: "日本語で,日本風に", russian: "по-япо\u0301нски" },
        { japanese: "講義室,聴講者", russian: "аудито\u0301рия" },
        { japanese: "アメリカの,アメリカ人の", russian: "америка\u0301нский" },
        { japanese: "イギリスの,イギリス人の", russian: "англи\u0301йский" },
        { japanese: "日本の,日本人の", russian: "япо\u0301нский" },
        { japanese: "少し", russian: "немно\u0301го" },
        { japanese: "既に", russian: "уже\u0301" },
        { japanese: "会話する", russian: "разгова\u0301ривать" }
      ]
    }

  ]
};
